name: Wiki Builder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        git submodule update --init
        cd schema
        npm ci
        ./node_modules/.bin/tsc
        cd ../import
        npm ci
        ./node_modules/.bin/tsc
        ./bin/convert
        cd ..
        node TiddlyWiki5/tiddlywiki.js ./twiki-standalone --build
        cp ./twiki-standalone/output/index.html ./new-wiki.html
        git stash
        git checkout gh-pages
        git config user.name "ewelton"
        git config user.email "ewelton@users.noreply.github.com"
        mv new-wiki.html wiki.html
        git add wiki.html
        git commit -m 'updated wiki'
        git push --force https://${{secrets.GH_OAUTH_TOKEN}}:x-oauth-basic@github.com/ewelton/ktest.git gh-pages
        echo npm ci
        echo npm run build --if-present
        echo npm test
      env:
        CI: true
