name: Wiki Builder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        git submodule update --init
        cd schema
        npm ci
        ./node_modules/.bin/tsc
        cd ..
        cd runner/TiddlyWiki5
        node tiddlywiki.js ../docker/content --build
        cd ../..
        cp runner/docker/content/output/index.html ./new-wiki.html
        git stash
        git checkout gh-pages
        git config user.name "ewelton"
        git config user.email "ewelton@users.noreply.github.com"
        mv new-wiki.html wiki.html
        git add wiki.html
        git commit -m 'updated wiki'
        cat .git/config
        git push --force https://f1e97377eb6038f490910561d4387d7e9f28d53e:x-oauth-basic@github.com/ewelton/ktest.git gh-pages:gh-pages
        echo npm ci
        echo npm run build --if-present
        echo npm test
      env:
        CI: true
