name: Wiki Builder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd schema
        npm ci
        ./node_modules/.bin/tsc
        cd ..
        cd runner/TiddlyWiki5
        node tiddlywiki.js ../docker/content --build
        cd ../..
        cp runner/docker/content/output/index.html ./wiki.html
        git checkout gh-pages
        git config user.name "ewelton"
        git config user.email "ewelton@users.noreply.github.com"
        git add  wiki.html
        git commit -m 'updated wiki'
        git push --force https://${{secrets.GITHUB_TOKEN}}@github.com/ewelton/ktest.git gh-pages:gh-pages
        echo npm ci
        echo npm run build --if-present
        echo npm test
      env:
        CI: true
